name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main
permissions:
  contents: write
  issues: write
jobs:
  super-lint:
    name: Super Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: super-linter/super-linter/slim@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          FILTER_REGEX_EXCLUDE: .github/ISSUE_TEMPLATE/.*|README.md
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true
          FAIL_ON_ERROR: true

  tag-verification:
    name: Tag Verification and Increment
    needs: super-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Verify and Increment Tag
        id: verify_tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
          release_branches: main

  development:
    name: Development Stage
    needs: tag-verification
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest

  build-and-publish:
    name: Build and Publish
    needs: development
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build Python package
        run: |
          python setup.py sdist bdist_wheel
      # - name: Publish Python package
      #   uses: pypa/gh-action-pypi-publish@v1.6.4
      #   with:
      #     user: __token__
      #     password: ${{ secrets.PYPI_API_TOKEN }}
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/myapp:${{ github.ref_name }} .
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/myapp:${{ github.ref_name }}

  create-release:
      name: Create Release
      needs: build-and-publish
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/main')
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Generate Release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ steps.verify_tag.outputs.new_tag }}
            release_name: Release ${{ steps.verify_tag.outputs.new_tag }}
            body: |
              ## Release Notes
              - Release notes for version ${{ steps.verify_tag.outputs.new_tag }}
            draft: false
            prerelease: false
